# 🧠 Introduction to NumPy

NumPy (Numerical Python) is a foundational library for scientific computing in Python. It offers a fast and flexible multidimensional array object, `ndarray`, and tools to work efficiently with large datasets.

🔧 **What can you do with NumPy?**
- Perform **mathematical** and **logical operations**
- Efficient **data reshaping, sorting**, and **filtering**
- Handle **input/output** operations with ease
- Perform **linear algebra** and **statistical** calculations
- Generate **random data** for simulations

➡️ NumPy is widely used in **Data Science**, **Machine Learning**, **Engineering**, and **Scientific Research**!


# 💻 Installing NumPy

🔹 In Google Colab, NumPy is **already installed** — you're good to go!

🔸 If you're working locally and need to install or update NumPy:

## 📦 Update pip (Python package manager):
```bash
!pip install --upgrade pip



---

## **Understanding `ndarray`** 🔢

### 🔢 The `ndarray` (N-Dimensional Array)

The core of NumPy is the **ndarray**, a powerful n-dimensional array object for storing and manipulating numerical data.

### 🧭 Dimensionality:
- **0D**: A single scalar value
- **1D**: A vector (e.g., `[1, 2, 3]`)
- **2D**: A matrix (e.g., `[[1, 2], [3, 4]]`)
- **3D+**: Tensors or stacked matrices

🏗️ These structures allow efficient data storage and manipulation, perfect for numerical computations and simulations!


---

## Array Creation Block 🛠️

In NumPy, arrays can be created in various ways. These functions allow you to create arrays with specific values or patterns:

- `np.array()`: Converts a list or another array to a NumPy array.
- `np.zeros()`: Creates an array filled with zeros.
- `np.ones()`: Creates an array filled with ones.
- `np.full()`: Creates an array filled with a specified value.
- `np.arange()`: Generates values within a specified range (like Python’s `range()` function).
- `np.linspace()`: Creates an array of evenly spaced values over a specified range.

### Example:


In [ ]:
import numpy as np

# Creating a 1D array
array1 = np.array([1, 2, 3])
print("1D Array:", array1)

# Creating a 2D array with 2 rows and 4 columns
array2 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
print("2D Array:\n", array2)

# np.zeros - creates an array filled with zeros
array3 = np.zeros(shape=(2, 3))
print("np.zeros:\n", array3)

# np.ones - creates an array filled with ones
array4 = np.ones(shape = (2, 3))
print("np.ones:\n", array4)

# np.full - creates an array filled with a specified value
array5 = np.full(shape=(2, 2), fill_value=7)
print("np.full:\n", array5)

# np.arange - creates an array with evenly spaced values within a given interval
array6 = np.arange(0, 10, 2)
print("np.arange:\n", array6)

# np.linspace - creates an array with evenly spaced numbers over a specified interval
array7 = np.linspace(start = 0,stop = 10,num = 5)
print("np.linspace:\n", array7)

## Array Manipulation Block 🔄

Array manipulation is essential in NumPy for transforming arrays in various ways:

- `reshape()`: Changes the shape of an array.
- `flatten()`: Flattens a multi-dimensional array into a 1D array.
- `transpose()`: Transposes the array (swaps rows and columns).
- `concatenate()`: Joins arrays along a specified axis.
- `stack()`: Joins arrays along a new axis.
- `split()`: Splits an array into multiple sub-arrays.

### Example:


In [ ]:
# Reshaping, flattening, and transposing
arr = np.array([[1, 2], [3, 4], [5, 6]])
print("Original Array:\n", arr)

reshaped_arr = arr.reshape(2, 3)
print("Reshaped Array:\n", reshaped_arr)

flattened_arr = arr.flatten()
print("Flattened Array:\n", flattened_arr)

transposed_arr = arr.T
print("Transposed Array:\n", transposed_arr)

# Concatenating arrays
arr2 = np.array([[7, 8], [9, 10], [11, 12]])
concatenated_arr = np.concatenate((arr, arr2), axis=0)
print("Concatenated Array:\n", concatenated_arr)

# Stacking arrays vertically and horizontally
stacked_arr = np.stack((arr, arr2), axis=0)
print("Stacked Array:\n", stacked_arr)

# Splitting arrays
split_arr = np.split(arr, 3, axis=0)
print("Split Arrays:", split_arr)


## Indexing and Slicing Block 🔍

NumPy arrays support powerful indexing and slicing methods:

- **Basic slicing**: Indexing arrays using standard `[]` notation.
- **Slicing tricks**: Advanced slicing techniques, such as `arr[start:stop:step]`.
- **Fancy indexing**: Using integer arrays or lists to index specific elements.
- **Boolean masking**: Creating a mask to index elements based on a condition.

### Example:


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", arr)

# Basic Slicing
sliced_arr = arr[0:2, 1:3]
print("Sliced Array (Basic):\n", sliced_arr)

# Slicing Tricks
step_sliced_arr = arr[::2, ::2]
print("Sliced Array (Step):\n", step_sliced_arr)

# Fancy Indexing
fancy_arr = arr[[0, 2], [0, 2]]
print("Fancy Indexed Array:", fancy_arr)

# Boolean Masking
mask = arr > 5
masked_arr = arr[mask]
print("Masked Array:", masked_arr)


## Math & Stats Block 📊

NumPy provides a wide range of mathematical and statistical functions:

- `np.mean()`: Calculates the mean of an array.
- `np.sum()`: Calculates the sum of all elements.
- `np.std()`: Calculates the standard deviation.
- `np.min()`, `np.max()`: Find the minimum and maximum values.
- **Broadcasting**: Allows operations between arrays of different shapes.

### Example:


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Statistical Operations
#axis=0 for column-wise, axis=1 for row-wise
mean = np.mean(arr)
sum_arr = np.sum(arr)
std = np.std(arr)
min_val = np.min(arr)
max_val = np.max(arr)

print(f"Mean: {mean}, Sum: {sum_arr}, Std Dev: {std}, Min: {min_val}, Max: {max_val}")

# Broadcasting
arr2 = np.array([10, 20, 30, 40, 50])
sum_broadcast = arr + arr2
print("Broadcasted Sum:", sum_broadcast)


## Tricks Block 🧙‍♂️

NumPy provides several advanced functions to make array manipulation easier:

- `np.where()`: Returns elements based on a condition.
- `np.unique()`: Finds the unique elements in an array.
- Masking: Using conditions to filter data.
- Vectorization: Avoids loops by applying operations element-wise.

### Example:


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# np.where
condition = arr > 3
where_result = np.where(condition, "greater", "lesser")
print("Where Result:", where_result)

# np.unique
arr2 = np.array([1, 2, 2, 3, 3, 3])
unique_elements = np.unique(arr2)
print("Unique Elements:", unique_elements)

# Masking
masked_arr = arr[arr > 2]
print("Masked Array:", masked_arr)

# Vectorization
vectorized_result = arr * 2
print("Vectorized Result:", vectorized_result)


## Bonus Tip Block 💡

### "Avoid loops—go vectorized!" 🚀

In NumPy, vectorization is the key to optimizing performance. Instead of using loops to process elements one by one, you can use NumPy's built-in operations to apply a function over the entire array in a vectorized manner, which is much faster.

### Example:


In [ ]:
# Avoiding loops by using vectorized operations
arr = np.array([1, 2, 3, 4, 5])

# Instead of a loop, use vectorized operation
result = arr * 2
print("Vectorized Operation:", result)


## Generating Data with NumPy 🧮

NumPy offers several functions to generate specific types of data:

- `np.arange()`: Generates values in a specified range.
- `np.linspace()`: Generates linearly spaced values.
- `np.random`: Random number generation.
- `reshape()`, `tile()`, `repeat()`, `full()`, `eye()`, and `diag()`.

### Example:


In [ ]:
# Generating data
arr1 = np.arange(0, 10, 2)
print("np.arange:", arr1)

arr2 = np.linspace(0, 10, 5)
print("np.linspace:", arr2)

random_arr = np.random.rand(2, 3)
print("Random Array:", random_arr)

full_arr = np.full((2, 2), 7)
print("np.full:", full_arr)

eye_arr = np.eye(3)
print("Identity Matrix (np.eye):\n", eye_arr)


## Inspecting Arrays 🔍

Inspecting the properties of NumPy arrays is essential for debugging and understanding array structures:

- `shape`: Returns the shape of the array.
- `ndim`: Returns the number of dimensions.
- `size`: Returns the total number of elements.
- `dtype`: Returns the data type of elements.
- Array printing tips for better visualization.

### Example:


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Shape: {arr.shape}")
print(f"Dimensions (ndim): {arr.ndim}")
print(f"Size: {arr.size}")
print(f"Data Type: {arr.dtype}")

## Advanced Tricks 🎩

These are some advanced tricks for working with arrays in NumPy:

- `np.isin()`: Checks if elements are present in another array.
- `np.any()`, `np.all()`: Checks for any or all True values.
- `np.setdiff1d()`: Returns the set difference of two arrays.

### Example:


In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

# np.isin
isin_result = np.isin(arr1, arr2)
print("Isin Result:", isin_result)

# np.any and np.all
any_result = np.any(arr1 > 3)
all_result = np.all(arr1 > 0)
print(f"Any greater than 3: {any_result}, All greater than 0: {all_result}")

# np.setdiff1d
set_diff = np.setdiff1d(arr1, arr2)
print("Set Difference:", set_diff)

## Performance Tips ⚡

Performance is a crucial aspect when working with large datasets. Here are some tips to optimize your NumPy code:

- **Vectorization vs loops**: Avoid using Python loops on NumPy arrays. Instead, use vectorized operations to apply calculations across entire arrays.
- **Axis Tips**: Many NumPy functions operate along specific axes, enabling faster computations by reducing the number of iterations.
- **Avoiding Object Arrays**: Use native NumPy types (e.g., `np.int32`, `np.float64`) instead of Python objects to improve performance.
- **Preallocating Memory**: Preallocate arrays when possible, instead of resizing arrays during runtime, which can be costly.

### Example:


In [ ]:
# Vectorization vs loops
arr = np.array([1, 2, 3, 4, 5])

# Avoid loop by using vectorized operation
result = arr * 10
print("Vectorized Result:", result)

# Axis example for sum
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
sum_axis_0 = np.sum(arr2, axis=0)  # Sum along columns
sum_axis_1 = np.sum(arr2, axis=1)  # Sum along rows
print("Sum along axis 0:", sum_axis_0)
print("Sum along axis 1:", sum_axis_1)

# Avoiding object arrays
arr3 = np.array([1, 2, 3], dtype=np.int32)
print("Array with np.int32 dtype:", arr3)

# Preallocating memory
preallocated_array = np.empty((1000000,), dtype=np.float64)  # Empty array, ready for filling
preallocated_array.fill(3.14)
print("Preallocated Array:", preallocated_array[:5])  # Display the first 5 elements


## Matrix Operations in NumPy 🔵

Performing mathematical operations on matrices is a key part of using NumPy effectively. Here’s how you can perform **matrix multiplication** and **element-wise operations**:

- `np.dot()` or `@` operator: Matrix multiplication (linear algebra style).
- `np.multiply()` or `*` operator: Element-wise multiplication.
- `np.divide()`: Element-wise division.
- `np.power()`: Raise each element to a given power.

### Example:

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# matrix multiplication using np.dot
result = np.dot(arr1, arr2)
print("Matrix Multiplication Result:\n", result)
print("Matrix Multiplication using @ operator:\n", arr1 @ arr2)

# Element-wise multiplication using np.multiply
elementwise_result = np.multiply(arr1, arr2)
print("Element-wise Multiplication Result:\n", elementwise_result)
print("Element-wise Multiplication using * operator:\n", arr1 * arr2)

# Element-wise division using np.divide
elementwise_division = np.divide(arr1, arr2)
print("Element-wise Division Result:\n", elementwise_division)

# Element-wise power using np.power
elementwise_power = np.power(arr1, 2)
print("Element-wise Power Result:\n", elementwise_power)

In [1]:
import numpy as np

# Original 1D array
array = np.array([1, 2, 3, 4, 5, 6])
print("Original array:")
print(array)

# Reshape using C-style (row-major order)
reshaped_c = np.reshape(array, (2, 3), order='C')
print("\nReshaped with order='C' (row-major):")
print(reshaped_c)

# Reshape using F-style (column-major order)
reshaped_f = np.reshape(array, (2, 3), order='F')
print("\nReshaped with order='F' (column-major):")
print(reshaped_f)


Original array:
[1 2 3 4 5 6]

Reshaped with order='C' (row-major):
[[1 2 3]
 [4 5 6]]

Reshaped with order='F' (column-major):
[[1 3 5]
 [2 4 6]]


In [4]:
import numpy as np
value= np.array([
[
    [1,2,3],
    [4,5,6],
],
[
    [1,2,3],
    [4,5,6]
]

])
print(value.ndim)

3


In [5]:
myarray=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
print (myarray)
print(type(myarray).__name__)
print (myarray.shape)
myarray[2,0]=17

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
ndarray
(4, 3)


In [ ]:
myarray=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
],dtype=int)
print(myarray[::2,::2]) #start,stop,step

[[1 3]
 [7 9]]


In [10]:
myarray=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
],dtype=int)
print(myarray.flatten())
print(myarray.flatten(order='F'))
print(myarray.shape)
print(myarray.size)
print(myarray.reshape((2,6),))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  4  7 10  2  5  8 11  3  6  9 12]
(4, 3)
12
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [30]:
import numpy as np
# 1D Array
array_1D = np.array([10, 11, 12, 13, 14])
# 2D Array
array_2D = np.array([[20, 30, 40, 50, 60], [43, 54, 65, 76, 87], [11, 22, 33, 44, 55]])
# 3D Array
array_3D = np.array([[[1, 2, 3, 4, 5], [11, 21, 31, 41, 51]], [[11, 12, 13, 14, 15], [51, 52, 53, 54, 5]]])

print(array_1D[0])
print(array_2D[0])
print(array_3D[0])
print(array_1D[0])
print(array_2D[0,0])
print(array_3D[0,0,0])
print(array_1D[-1])
print(array_2D[-1,-1])
print(array_3D[-1,-1,-1])

10
[20 30 40 50 60]
[[ 1  2  3  4  5]
 [11 21 31 41 51]]
10
20
1
14
55
5


Slice the first column of the 2-D array.
Slice the last two columns of the 2-nd row of the 2-D array
Slice the 2-nd row of the 2-D array excluding the last two columns


In [ ]:
import numpy as np

array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])

# Slice the first column of the 2-D array.
print(array_2D[:,0])
# Slice the last two columns of the 2-nd row of the 2-D array
print(array_2D[1, -2:])
# Slice the 2-nd row of the 2-D array excluding the last two columns
print(array_2D[1,:-2])

[10 11 12 13 14]
[[20 30 40 50 60]
 [43 54 65 76 87]
 [11 22 33 44 55]]
[[[ 1  2  3  4  5]
  [11 21 31 41 51]]

 [[11 12 13 14 15]
  [51 52 53 54  5]]]
[20 43 11]
----------
[60 87 55]


The first one should be "empty"
The second one should be full of 0s
The third one should be full of 1s
The last one should be full of 2s
Generate 4 more arrays. This time, they should be 2 by 4 arrays

In [ ]:
# Generate 4 arrays of size 10:

# The first one should be "empty"
print(np.empty(10))
# The second one should be full of 0s
print(np.zeros((5,2)))
# The third one should be full of 1s
print(np.ones((2,5)))
# The last one should be full of 2s
print(np.full(10, fill_value= 2))
# Generate 4 more arrays. This time, they should be 2 by 4 arrays
# The first one should be "empty"
print(np.empty((2,4)))
# The second one should be full of 0s
print(np.zeros((2,4)))
# The third one should be full of 1s
print(np.ones((2,4)))
# The last one should be full of 2s
print(np.full((2,4), fill_value= 2))

Display the first element (not necessarily individual element) for each of the 3 arrays we defined above
Call the first individual element of the each of the 3 arrays.
Uses negative indices to display the last element of each array


In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print(arr.max(axis=0)) # colonnes
print(arr.max(axis=1)) # lignes
print(arr.max()) # toute la matrice

print("-"*30)

print(arr.min(axis=0)) # colonnes
print(arr.min(axis=1)) # lignes
print(arr.min()) # toute la matrice

print("-"*30)

print(arr.mean(axis=0)) # colonnes
print(arr.mean(axis=1)) # lignes
print(arr.mean()) # toute la matrice

print("-"*30)

print(arr.std(axis=0)) # colonnes
print(arr.std(axis=1)) # lignes
print(arr.std()) # toute la matrice